// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDavHVoCT9ZIKMScyMm6vSsWqw2yLxRm94',
    appId: '1:103195755777:web:f99fbbade1b2604b104700',
    messagingSenderId: '103195755777',
    projectId: 'fidelity-a30d6',
    authDomain: 'fidelity-a30d6.firebaseapp.com',
    storageBucket: 'fidelity-a30d6.firebasestorage.app',
    measurementId: 'G-4YXKWYM6DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6frBJVcLufOie-vmKZdH9LWRsD6lj0cU',
    appId: '1:103195755777:android:fefa424ddb9a1095104700',
    messagingSenderId: '103195755777',
    projectId: 'fidelity-a30d6',
    storageBucket: 'fidelity-a30d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC33iYMWvQeQ0PZGC1mSEh3Vt7H9_3UfIQ',
    appId: '1:103195755777:ios:2a7ae11255fbc4e5104700',
    messagingSenderId: '103195755777',
    projectId: 'fidelity-a30d6',
    storageBucket: 'fidelity-a30d6.firebasestorage.app',
    iosBundleId: 'com.example.fidelityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC33iYMWvQeQ0PZGC1mSEh3Vt7H9_3UfIQ',
    appId: '1:103195755777:ios:2a7ae11255fbc4e5104700',
    messagingSenderId: '103195755777',
    projectId: 'fidelity-a30d6',
    storageBucket: 'fidelity-a30d6.firebasestorage.app',
    iosBundleId: 'com.example.fidelityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDavHVoCT9ZIKMScyMm6vSsWqw2yLxRm94',
    appId: '1:103195755777:web:39343993b8d1f0ea104700',
    messagingSenderId: '103195755777',
    projectId: 'fidelity-a30d6',
    authDomain: 'fidelity-a30d6.firebaseapp.com',
    storageBucket: 'fidelity-a30d6.firebasestorage.app',
    measurementId: 'G-ZCVQ0SPFK8',
  );
}
